global:
  datacenter: dc1
  name: consul
  logLevel: debug
  enabled: false
  imageK8S: consul-k8s-control-plane-dev:blueberry
  image: consul-dev:local

connectInject:
  enabled: true
  default: true

server:
  enabled: true
  replicas: 1

client:
  enabled: true
  grpc: true

ui:
  enabled: true
  service:
    type: NodePort
