global:
  datacenter: dc1
  name: consul
  logLevel: debug
  enabled: false
  imageK8S: consul-k8s-control-plane-dev:blueberry

connectInject:
  enabled: true
  replicas: 1
  transparentProxy:
    defaultEnabled: true
    defaultOverwriteProbes: true
  k8sAllowNamespaces: ["*"]
  consulNamespaces:
    mirroringK8S: true

server:
  enabled: true
  replicas: 1

client:
  enabled: true
  grpc: true

ui:
  enabled: true
  service:
    type: NodePort
