services:
  consul-server1:
    image: consul-dev:latest
    container_name: consul-server1
    restart: always
    volumes:
      - ./configs/server.hcl:/consul/config/server.hcl
    networks:
      dc1:
        ipv4_address: 10.6.0.2
    ports:
      - "8500:8500"
      - "8600:8600"
    environment:
      CONSUL_LICENSE: ${CONSUL_LICENSE}
    command: "agent -bootstrap"
    privileged: true

  service-bender-default:
    image: hashicorp/http-echo:alpine
    container_name: "service-bender-default"
    command: "-listen=:8080 -text='hello world'"
    ports:
      - "8080:8080"
      - "19002:19000"
    networks:
      dc1:
        ipv4_address: 10.6.0.100

  service-bender-default-envoy:
    image: consul-envoy:local
    container_name: service-bender-default-envoy
    volumes:
      - ./configs/bender.hcl:/consul/config/bender.hcl
    environment:
      CONSUL_LICENSE: ${CONSUL_LICENSE}
      CONSUL_HTTP_ADDR: 10.6.0.2:8500
      CONSUL_GRPC_ADDR: 10.6.0.2:8502
      SERVICE_CONFIG: /consul/config/bender.hcl
    command: "consul connect envoy -sidecar-for bender -admin-bind=0.0.0.0:19000"
    network_mode: "service:service-bender-default"

  service-zoidberg-default:
    image: hashicorp/http-echo:alpine
    container_name: "service-zoidberg-default"
    command: "-listen=:8081 -text='hello world'"
    environment:
      # TOKEN is an example jwt token that is signed by the generated jwk in the jwk-intention file and the my-key.jwk file, generated from https://www.scottbrady91.com/tools/jwt
      # JWT HEADER:
      # {
      #  "typ": "JWT",
      #  "alg": "PS256",
      #  "kid": "C-E1nCjwgBC-PuGM2O467FRDhKx8AkVctISAbo3riew"
      # }
      # JWT Payload
      # {
      #  "iss": "local"
      # }
      TOKEN: "eyJ0eXAiOiJKV1QiLCJhbGciOiJQUzI1NiIsImtpZCI6IkMtRTFuQ2p3Z0JDLVB1R00yTzQ2N0ZSRGhLeDhBa1ZjdElTQWJvM3JpZXcifQ.eyJpc3MiOiJsb2NhbCJ9.GV0lwSP6DWvVaOS1FgMxXRLeS4EvZngBHxUppqSUlVB-j4E08zMctfNO3h4i3c2OCLif1iEMks66BeXzZbuApeaKPZpqIuV8WNwsCJe5ehPPaxfMJ9KviGoFrJnJ_Y7g-Ov7kByoeeOSwdhYJ7kggpUoH0WGnFnWiOKniG-f9iyu-Bzi8Fn_Arvr-SaX4pDngsCAjC5qKb1CbWm-KV_gyUSls3wAsrV_8L4CmUqHw-Pu3DRyxO_GHfERHf0dJeLlxfGOLSQeunCWck1ETLlHk31fUjSE9zsmv2z_OaLFf86Rei4_IzX9mC__amGFS3voCKrdqueqZHdEnGGmjqLWCw"
    ports:
      - "8081:8081"
      - "19001:19000"
    networks:
      dc1:
        ipv4_address: 10.6.0.200

  service-zoidberg-default-envoy:
    image: consul-envoy:local
    container_name: service-zoidberg-default-envoy
    volumes:
      - ./configs/zoidberg.hcl:/consul/config/zoidberg.hcl
    environment:
      CONSUL_LICENSE: ${CONSUL_LICENSE}
      CONSUL_HTTP_ADDR: 10.6.0.2:8500
      CONSUL_GRPC_ADDR: 10.6.0.2:8502
      SERVICE_CONFIG: /consul/config/zoidberg.hcl
    command: "consul connect envoy -sidecar-for zoidberg -admin-bind=0.0.0.0:19000"
    network_mode: "service:service-zoidberg-default"


networks:
  dc1:
    driver: bridge
    ipam:
     config:
       - subnet: 10.6.0.0/16
