services:
  consul-server1:
    image: consul:local
    container_name: consul-server1
    restart: always
    volumes:
      - ./configs/server.hcl:/consul/config/server.hcl
    networks:
      dc1:
        ipv4_address: 10.6.0.2
    ports:
      - "8500:8500"
      - "8600:8600"
    environment:
      CONSUL_LICENSE: ${CONSUL_LICENSE}
    command: "agent -bootstrap"
    privileged: true

  service-bender-default:
    image: hashicorp/http-echo:alpine
    container_name: "service-bender-default"
    command: "-listen=:8080 -text='hello world'"
    ports:
      - "8080:8080"
      - "19000:19000"
    networks:
      dc1:
        ipv4_address: 10.6.0.100

  service-bender-default-envoy:
    image: consul-envoy:local
    container_name: service-bender-default-envoy
    volumes:
      - ./configs/bender.hcl:/consul/config/bender.hcl
    environment:
      CONSUL_LICENSE: ${CONSUL_LICENSE}
      CONSUL_HTTP_ADDR: 10.6.0.2:8500
      CONSUL_HTTP_TOKEN: root
      CONSUL_GRPC_ADDR: 10.6.0.2:8502
      SERVICE_CONFIG: /consul/config/bender.hcl
    command: "consul connect envoy -sidecar-for bender -admin-bind=0.0.0.0:19000"
    network_mode: "service:service-bender-default"

  service-zoidberg-default:
    image: hashicorp/http-echo:alpine
    container_name: "service-zoidberg-default"
    command: "-listen=:8081 -text='hello world'"
    environment:
      SIMPLE_TOKEN: "eyJ0eXAiOiJKV1QiLCJhbGciOiJQUzI1NiIsImtpZCI6IkMtRTFuQ2p3Z0JDLVB1R00yTzQ2N0ZSRGhLeDhBa1ZjdElTQWJvM3JpZXcifQ.eyJpc3MiOiJsb2NhbCJ9.GV0lwSP6DWvVaOS1FgMxXRLeS4EvZngBHxUppqSUlVB-j4E08zMctfNO3h4i3c2OCLif1iEMks66BeXzZbuApeaKPZpqIuV8WNwsCJe5ehPPaxfMJ9KviGoFrJnJ_Y7g-Ov7kByoeeOSwdhYJ7kggpUoH0WGnFnWiOKniG-f9iyu-Bzi8Fn_Arvr-SaX4pDngsCAjC5qKb1CbWm-KV_gyUSls3wAsrV_8L4CmUqHw-Pu3DRyxO_GHfERHf0dJeLlxfGOLSQeunCWck1ETLlHk31fUjSE9zsmv2z_OaLFf86Rei4_IzX9mC__amGFS3voCKrdqueqZHdEnGGmjqLWCw"
      DOCTOR_TOKEN: "eyJ0eXAiOiJKV1QiLCJhbGciOiJQUzI1NiIsImtpZCI6IkMtRTFuQ2p3Z0JDLVB1R00yTzQ2N0ZSRGhLeDhBa1ZjdElTQWJvM3JpZXcifQ.eyJpc3MiOiJsb2NhbCIsInJvbGUiOiJkb2N0b3IifQ.FfgpzjMf8Evh6K-fJ1cLXklfIXOm-vojVbWlPPbGVFtzxZ9hxMxoyAY_G8i36SfGrpUlp-RJ6ohMvprMrEgyRgbenu7u5kkm5iGHW-zpMus4izXRxPELBcpWOGF105HIssT2NYRstXieNR8EVzvGfLdvR0GW8ttEERgseqGvuAfdb4-aNYsysGwUUHbsZjazA6H1rZmWqHdCLOJ2ZwFsIdckO9CadnkyTILpcPUmLYyUVJdtlLGOySb0GG8c_dPML_IR5jSXCSUZt6S2JBNBNBdqukrlqpA-fIaaWft0dbWVMhv8DqPC8znult8dKvLZ1qXeU0itsqqJUyE16ihJjw"
    ports:
      - "8081:8081"
      - "19001:19000"
    networks:
      dc1:
        ipv4_address: 10.6.0.200

  service-zoidberg-default-envoy:
    image: consul-envoy:local
    container_name: service-zoidberg-default-envoy
    volumes:
      - ./configs/zoidberg.hcl:/consul/config/zoidberg.hcl
    environment:
      CONSUL_LICENSE: ${CONSUL_LICENSE}
      CONSUL_HTTP_ADDR: 10.6.0.2:8500
      CONSUL_HTTP_TOKEN: root
      CONSUL_GRPC_ADDR: 10.6.0.2:8502
      SERVICE_CONFIG: /consul/config/zoidberg.hcl
    command: "consul connect envoy -sidecar-for zoidberg -admin-bind=0.0.0.0:19000"
    network_mode: "service:service-zoidberg-default"

  service-nibbler-default:
    image: hashicorp/http-echo:alpine
    container_name: "service-nibbler-default"
    command: "-listen=:8082 -text='hello world'"
    environment:
      SIMPLE_TOKEN: "eyJ0eXAiOiJKV1QiLCJhbGciOiJQUzI1NiIsImtpZCI6IkMtRTFuQ2p3Z0JDLVB1R00yTzQ2N0ZSRGhLeDhBa1ZjdElTQWJvM3JpZXcifQ.eyJpc3MiOiJsb2NhbCJ9.GV0lwSP6DWvVaOS1FgMxXRLeS4EvZngBHxUppqSUlVB-j4E08zMctfNO3h4i3c2OCLif1iEMks66BeXzZbuApeaKPZpqIuV8WNwsCJe5ehPPaxfMJ9KviGoFrJnJ_Y7g-Ov7kByoeeOSwdhYJ7kggpUoH0WGnFnWiOKniG-f9iyu-Bzi8Fn_Arvr-SaX4pDngsCAjC5qKb1CbWm-KV_gyUSls3wAsrV_8L4CmUqHw-Pu3DRyxO_GHfERHf0dJeLlxfGOLSQeunCWck1ETLlHk31fUjSE9zsmv2z_OaLFf86Rei4_IzX9mC__amGFS3voCKrdqueqZHdEnGGmjqLWCw"
      PET_TOKEN: "eyJ0eXAiOiJKV1QiLCJhbGciOiJQUzI1NiIsImtpZCI6IkMtRTFuQ2p3Z0JDLVB1R00yTzQ2N0ZSRGhLeDhBa1ZjdElTQWJvM3JpZXcifQ.eyJpc3MiOiJsb2NhbCIsInJvbGUiOiJwZXQifQ.l94rJayGGTMB426HwEw5ipSjaIHjm-UWDHiBAlB_Slmi814AxAfl_0AdRwSz67UDnkoygKbvPpR5xUB03JCXNshLZuKLegWsBeQg_OJYvZGmFagl5NglBFvH7Jbta4e1eQoAxZI6Xyy1jHbu7jFBjQPVnK8EaRvWoW8Pe8a8rp_5xhub0pomhvRF6Pm5kAS4cMnxvqpVc5Oo5nO7ws_SmoNnbt2Ok14k23Zx5E2EWmGStOfbgFsdbhVbepB2DMzqv1j8jvBbwa_OxCwc_7pEOthOOxRV6L3ZjgbRSB4GumlXAOCBYXD1cRLgrMSrWB1GkefAKu8PV0Ho1px6sI9Evg"
    ports:
      - "8082:8082"
      - "19002:19000"
    networks:
      dc1:
        ipv4_address: 10.6.0.250

  service-nibbler-default-envoy:
    image: consul-envoy:local
    container_name: service-nibbler-default-envoy
    volumes:
      - ./configs/nibbler.hcl:/consul/config/nibbler.hcl
    environment:
      CONSUL_LICENSE: ${CONSUL_LICENSE}
      CONSUL_HTTP_ADDR: 10.6.0.2:8500
      CONSUL_HTTP_TOKEN: root
      CONSUL_GRPC_ADDR: 10.6.0.2:8502
      SERVICE_CONFIG: /consul/config/nibbler.hcl
    command: "consul connect envoy -sidecar-for nibbler -admin-bind=0.0.0.0:19000"
    network_mode: "service:service-nibbler-default"

networks:
  dc1:
    driver: bridge
    ipam:
     config:
       - subnet: 10.6.0.0/16
