kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: gwtime
nodes:
- role: control-plane
  image: kindest/node:v1.25.3
  extraPortMappings:
  - containerPort: 30000
    hostPort: 40600
  - containerPort: 30001
    hostPort: 40601
  - containerPort: 30002
    hostPort: 40602
