apiVersion: consul.hashicorp.com/v1alpha1
kind: GatewayPolicy
metadata:
  name: gw-policy
spec:
  targetRef:
    name: api-gateway
    sectionName: listener-one
    group: gateway.networking.k8s.io/v1beta1
    kind: Gateway
  override:
    jwt:
      providers:
      - name: "api-jwt-provider"
