apiVersion: consul.hashicorp.com/v1alpha1
# HTTPRoute routes HTTP requests to backend services.
kind: RouteAuthFilter
metadata:
  name: auth-filter
spec:
  jwt:
    providers:
    - name: "local"
      verifyClaims:
      - path:
          - role
            perm
        value: admin
