global:
  name: consul
  imageK8S: hashicorp/consul-k8s-control-plane:1.1.2
  image: hashicorp/consul:1.15.3
  peering:
    enabled: true
  tls:
    enabled: true

meshGateway:
  enabled: true
  replicas: 3
  service:
    type: LoadBalancer
    annotations: |
      "service.beta.kubernetes.io/aws-load-balancer-internal": "true"

server:
  enabled: true
  replicas: 1

ui:
  enabled: true
  service:
    type: LoadBalancer
