---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: bender
  namespace: default
spec:
  protocol: http
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bender
  name: bender
  namespace: default
spec:
  ports:
  - port: 8080
    name: high
    protocol: TCP
    targetPort: 8080
  selector:
    app: bender
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bender
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bender
  name: bender
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bender
  template:
    metadata:
      labels:
        app: bender
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
    spec:
      serviceAccountName: bender
      containers:
      - image: hashicorp/http-echo:alpine
        args: ["-listen=:8080", "-text='bender bender bender'"]
        name: bender
        env:
        - name: SERVICE_NAME
          value: bender
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONSUL_HTTP_TOKEN
          value: root
        ports:
        - containerPort: 8080
