---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: zoidberg
  namespace: default
spec:
  protocol: http
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: zoidberg
  name: zoidberg
  namespace: default
spec:
  ports:
  - port: 8081
    name: high
    protocol: TCP
    targetPort: 8081
  selector:
    app: zoidberg
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: zoidberg
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zoidberg
  name: zoidberg
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zoidberg
  template:
    metadata:
      labels:
        app: zoidberg
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
    spec:
      serviceAccountName: zoidberg
      containers:
      - image: hashicorp/http-echo:alpine
        args: ["-listen=:8081", "-text='why not zoidberg?'"]
        name: zoidberg
        env:
        - name: SERVICE_NAME
          value: zoidberg
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONSUL_HTTP_TOKEN
          value: root
        - name: SIMPLE_TOKEN
          value: "eyJ0eXAiOiJKV1QiLCJhbGciOiJQUzI1NiIsImtpZCI6IkMtRTFuQ2p3Z0JDLVB1R00yTzQ2N0ZSRGhLeDhBa1ZjdElTQWJvM3JpZXcifQ.eyJpc3MiOiJsb2NhbCJ9.GV0lwSP6DWvVaOS1FgMxXRLeS4EvZngBHxUppqSUlVB-j4E08zMctfNO3h4i3c2OCLif1iEMks66BeXzZbuApeaKPZpqIuV8WNwsCJe5ehPPaxfMJ9KviGoFrJnJ_Y7g-Ov7kByoeeOSwdhYJ7kggpUoH0WGnFnWiOKniG-f9iyu-Bzi8Fn_Arvr-SaX4pDngsCAjC5qKb1CbWm-KV_gyUSls3wAsrV_8L4CmUqHw-Pu3DRyxO_GHfERHf0dJeLlxfGOLSQeunCWck1ETLlHk31fUjSE9zsmv2z_OaLFf86Rei4_IzX9mC__amGFS3voCKrdqueqZHdEnGGmjqLWCw"
        - name: DOCTOR_TOKEN
          value: "eyJ0eXAiOiJKV1QiLCJhbGciOiJQUzI1NiIsImtpZCI6IkMtRTFuQ2p3Z0JDLVB1R00yTzQ2N0ZSRGhLeDhBa1ZjdElTQWJvM3JpZXcifQ.eyJpc3MiOiJsb2NhbCIsInJvbGUiOiJkb2N0b3IifQ.FfgpzjMf8Evh6K-fJ1cLXklfIXOm-vojVbWlPPbGVFtzxZ9hxMxoyAY_G8i36SfGrpUlp-RJ6ohMvprMrEgyRgbenu7u5kkm5iGHW-zpMus4izXRxPELBcpWOGF105HIssT2NYRstXieNR8EVzvGfLdvR0GW8ttEERgseqGvuAfdb4-aNYsysGwUUHbsZjazA6H1rZmWqHdCLOJ2ZwFsIdckO9CadnkyTILpcPUmLYyUVJdtlLGOySb0GG8c_dPML_IR5jSXCSUZt6S2JBNBNBdqukrlqpA-fIaaWft0dbWVMhv8DqPC8znult8dKvLZ1qXeU0itsqqJUyE16ihJjw"
        ports:
        - containerPort: 8081
